# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Louis Bianchini
email: lbianch85@gmail.com
email_display: lbianch85
description: "Physicist : Programmer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lbianch.com"
#twitter_username: lbianch85
github_username:  lbianch
linkedin_username: louisbianchini

# Build settings
markdown: kramdown
